BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS energy_balance (
  user_id INTEGER PRIMARY KEY,
  engergy INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS custom_roles (
  role_id INTEGER PRIMARY KEY,
  user_id INTEGER UNIQUE NOT NULL,
  expires_at TIMESTAMP,
  auto_renewal BOOLEAN DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS app_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
COMMIT;
